test_set = Set.new()
print(test_set)
print(getmetatable(test_set))
test_set:insert(10)
test_set:insert(10)
test_set:insert(10)
test_set:insert(20)
print(test_set:count(10))
print("size:", test_set:size())

test_queue = Queue.new()
print(test_queue)
print(getmetatable(test_queue))
print("size:", test_queue:size())
test_queue:push(1)
print("size:", test_queue:size())
print(test_queue:pop())
print("size:", test_queue:size())
