test_set = containers.set_new()
print(test_set)
print(getmetatable(test_set))
containers.set_insert(test_set, 10)
containers.set_insert(test_set, 10)
containers.set_insert(test_set, 10)
containers.set_insert(test_set, 20)
print(containers.set_count(test_set, 10))
print(containers.set_size(test_set))

test_queue = containers.queue_new()
print(test_queue)
print(getmetatable(test_queue))
print("size:", containers.queue_size(test_queue))
containers.queue_push(test_queue, 1)
print("size:", containers.queue_size(test_queue))
print(containers.queue_pop(test_queue))
print("size:", containers.queue_size(test_queue))

--print(containers.queue_size(1))
